learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views
app_name='basic_app'
urlpatterns = [
path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
path('',views.index,name='index'),
path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
    # Create relationship (don't inherit from User!)
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE )

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method=='POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <li><a class="navbar-brand" href="{% url 'index' %}">Default</a></li>
        <li><a class="navbar-brand" href="{% url 'admin:index' %}">admin</a></li>
        <li><a class="navbar-brand" href="{% url 'basic_app:register' %}">register</a></li>
        {% if user_is_authenticated %}
        <li><a class="navbar-brand" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a class="navbar-brand" href="{% url 'basic_app:user_login' %}">login</a></li>
        {%endif%}

       </div>
     </nav>
     <div class="container">
         {% block body_block %}
         {% endblock%}
         </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html"%}
{% block body_block %}
<h1>Welcome people </h1>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html"%}
{% block body_block %}
<<div class="jumbotron">
  <h1>login please</h1>
  <form  action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">username:</label>
    <input type="text" name="username" value="">
<label for="password">password:</label>
<input type="password" name="password" >
<input type="submit" name="" value="login">
  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>thanknyu</h1>
  {% else %}
  <h1>register here</h1>
  <h2>fill out the form</h2>
  <form enctype="multipart/form-data"  method="POST">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="register">
  </form>
  {% endif %}
</div>
{% endblock%}